# Experiment 5

**Topics of Experiment 5**

*   Using `for` loop in Python.
*   Using `if elif else` in Python.
*   Function and Methods.
*   numpy library.


In [1]:
Student = "Amit Sweiry"    # Student Name
ID = "322816323"         # ID
print(Student, ID)

Amit Sweiry 322816323


### Exercise 1 - 35 points

Create a function called `ExtractNonVowelEnclosedWords`.

This function should accept a single string as its input and return a list containing only the words that **start and end** with a non-vowel (NOT - (A, E, I, O, U)). The function should be case-insensitive, meaning it should recognize consonants regardless of whether they are uppercase or lowercase.

You are allowed to use the `.lower()` method if necessary (for more information, you can use `help(str.lower)`).

**Example 1:**

```python
sampleString = "I'm in a hurry because my trip isn't coming soon, so I have to find another way to get there."
resultList = ExtractNonVowelEnclosedWords(sampleString)
```
resultList → ['hurry', 'my', 'trip', 'coming', 'soon', 'find', 'way', 'get']

**Example 2:**

```python
sampleString = "Every choice leads to a different path."
resultList = ExtractNonVowelEnclosedWords(sampleString)
```
resultList → ['leads', 'different', 'path']

In [2]:
# answer exe 1 here!
def ExtractNonVowelEnclosedWords(string):
    chars = 'aeiou'
    string = string.lower()
    strList = string.split()
    tmpList = []
    for word in strList:
      if(chars.find(word[0]) == -1 and chars.find(word[-1]) == -1 ):
        tmpList.append(word)
    return tmpList

In [3]:
print(ExtractNonVowelEnclosedWords("I'm in a hurry because my trip isn't coming soon, so I have to find another way to get there."))
print(ExtractNonVowelEnclosedWords("to do something bad just because someone else has done someth"))

['hurry', 'my', 'trip', 'coming', 'soon,', 'find', 'way', 'get', 'there.']
['something', 'bad', 'just', 'has', 'someth']


### Exercise 2 - 35 points

Define a function named `countWordsNotEndingWithChars`.

The function should take two inputs:
1. A string made up of words.
2. A set of characters (string) to filter out words that end with any of them.

The function should return a dictionary where each key is a word that **doesn't end** with any of the given characters, and each value is the number of occurrences of that word. The function should be case-insensitive, which means it should recognize vowels regardless of whether they are uppercase or lowercase.

**Example:**

```python
myStr = 'Hello Hello We DO He no No no we'
chars = 'oE'
stringHist = countWordsNotEndingWithChars(myStr, chars)
```
stringHist → {}. **(The order of the words/keys does not matter)**

**Another Example:**

```python
myStr = 'Apple Banana Cherry Apple apricot banana'
chars = 'EY'
stringHist = countWordsNotEndingWithChars(myStr, chars)
```
stringHist → {'banana': 2, 'apricot': 1}. **(The order of the words/keys does not matter)**

In [4]:
# answer exe 2 here!
def countWordsNotEndingWithChars(line, chars):
    line = line.lower()
    lineList = line.split()
    chars = chars.lower()
    tmpDict = {}
    for word in lineList:
      if(chars.find(word[-1]) == -1):
        if(tmpDict.get(word)):
          tmpDict[word] = tmpDict[word] + 1
        else:
          tmpDict[word] = 1
    return tmpDict

In [5]:
print(countWordsNotEndingWithChars('Apple Banana Cherry Apple apricot banana', 'EY'))

{'banana': 2, 'apricot': 1}


### Exc 3 - 30 points

Define a function named `PlusMat`.
The function input is two parameters.

1.   `ms` – even number. represents the size of the matrix.
2.   `width_half` – natural number. Represents the thickness of the strips of the ones, the thickness of the entire strip is **twice** the `width_half`.
It should also have a default value of 1.
3. Check that both `ms` and `width_half` are numerical objects (using "[numbers.Number](https://stackabuse.com/python-check-if-variable-is-a-number/)"!!)
If not, return None.

the function returns a matrix that is an ndarray array of dtype int.
The plus is located exactly in the middle of the matrix.

**example 1:**

```pyton
plus_1 = PlusMat(4)
print(plus_1)

[[0 1 1 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 1 1 0]]
```

**example 2:**

```pyton
plus_2 = PlusMat(8, 2)
print(plus_2)

[[0 0 1 1 1 1 0 0]
 [0 0 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 0 0]
 [0 0 1 1 1 1 0 0]]
```

**example 3:**

```pyton
plus_3 = PlusMat(7, 2)
print(plus_3)

[[0 0 1 1 1 1 0 0]
 [0 0 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 0 0]
 [0 0 1 1 1 1 0 0]]
```

In [20]:
import numpy as np
import numbers
# answer exe 3 here!
def PlusMat(ms, width_half = 1):
    if(isinstance(ms, numbers.Number) and isinstance(width_half, numbers.Number)):
      if(ms%2):
        ms = ms + 1
      mat = np.zeros((ms,ms), dtype=np.int64)
      tmpRange = range((int(ms/2) - width_half), (int(ms/2) + width_half))
      mat[tmpRange, :] = 1
      mat[:, tmpRange] = 1
      return mat
    else:
      return None

In [ ]:
plus_1 = PlusMat(4)
print(plus_1)
print(" ")

plus_2 = PlusMat(8, 2)
print(plus_2)
print(" ")

plus_3 = PlusMat(7, 2)
print(plus_3)
print(" ")

plus_4 = PlusMat(16,3)
print(plus_4)